# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      #- run: npm test
      #- name: Upload coverage to Codecov
        #uses: codecov/codecov-action@v1
        #with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          #directory: ./docs/coverage/
          #flags: unittests # optional
          #name: codecov-foundryvtt-simple-calendar # optional
          #fail_ci_if_error: true # optional (default = false)
          #verbose: true # optional (default = false)
